server:
  port: 8080
spring:
    application:
        name: hm-gateway
    cloud:
      nacos:
        server-addr: 192.168.110.131:8848
      gateway:
        routes:
          - id: item-service
            uri: lb://item-service
            predicates:
              - Path=/items/**,/search/**
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/address/**,/users/**
          - id: trade-service
            uri: lb://trade-service
            predicates:
              - Path=/orders/**
          - id: pay-service
            uri: lb://pay-service
            predicates:
              - Path=/pay-orders/**
          - id: cart-service
            uri: lb://cart-service
            predicates:
              - Path=/carts/**
        default-filters:
          - AddRequestHeader=X-Source-Red, Blue-{segment}
        gateway:
          routes:
            - id: item-service
              uri: lb://item-service
              predicates:
                - Path=/items/**,/search/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/addresses/**,/users/**
          default-filters:
            - AddRequestHeader=truth, anyone long-press like button will be rich
            - PrintAny=1,2,3
